version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1
      - MYSQL_DATABASE=auth_service
    depends_on:
      - mysql
    networks:
      - backend

  user-service:
    build:
      context: ./user-service
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1
      - MYSQL_DATABASE=user_service
    depends_on:
      - mysql
    networks:
      - backend

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - user-service
    networks:
      - backend

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: mysql_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
